n = input('Digite algo ')
print('O tipo primitivo desse valor é',type(n))
print('Só tem espaços', n.isspace())
print('Ele é um número? ',n.isnumeric())
print('Ele é uma alfabetico? ',n.isalpha())
print('Ele é alfanumerico? ',n.isalnum())
print('Esta em maiusculas? ' ,n.isupper())
print('Esta em minusculas? ' ,n.islower())
print('Esta em Captalizada? '. n.iscapitalize())

